Algoritmo "meuPrimeiroAlgoritmo"
// autor: Jussara Alves
// data: 15/11/2021
// horario: 19:45
var
//seçao de declaracao de variaveis
nome:caracter
idade:inteiro
altura:real
casado:logico

inicio
//secao de comandos
escreval("Digite seu nome: ")
leia(nome)
escreval("Digite sua idade: ")
leia(idade)
escreval("Digite sua altura")
leia(altura)

escreval("Seu nome é ", nome, ", sua idade é ", idade, ", e sua Altura é ",altura)

fimalgoritmo